version: "3.9"
volumes:
    prometheus_data: {}
    grafana_data: {}

services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        hostname: prometheus
        restart: always
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        ports:
            - 9090:9090
        networks: 
            - monitoring

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        hostname: grafana
        environment:
            - GF_USERS_ALLOW_SIGN_UP=false
        volumes:
            - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
            - grafana_data:/var/lib/grafana
        ports:
            - 3000:3000
        depends_on:
            - prometheus
        networks: 
            - monitoring

    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        volumes:
            - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
            - ./data/alertmanager:/data
        ports:
            - 9093:9093
        networks:
            - "monitoring"

networks: 
    monitoring:
