global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx, http_post_2xx]
    static_configs:
      - targets:
        - https://olist.com
        - https://blog.olist.com
        - https://marketplaces.com.br
        - https://app.olist.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: website_instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

rule_files:
  - 'rules.yml'

alerting:
   alertmanagers:
     - static_configs: 
         - targets:
             - alertmanager:9093 