modules:
  http_2xx:
    prober: http

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      headers:
        Content-Type: application/json
      body: '{}'
  
  http_basic_auth_olist_webapp:
      prober: http
      timeout: 5s
      http:
        method: POST
        headers:
          Host: "app.olist.com"
        basic_auth:
          username: "william.stiehler@evoluinfo.com.br"
          password: "olist123"